trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroup: 'k8s-monitoring-v2'
  location: 'westeurope'
  clusterName: 'aks-lab-cluster'

stages:
- stage: DeployAKS
  displayName: 'AKS ve Monitoring Kurulumu'
  jobs:
  - job: AzureCLI
    displayName: 'Azure CLI ile Altyapı Kontrol Et ve Kur'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SC-Azure-Erdem'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # 1. Resource Group oluştur (Zaten varsa hata vermez, günceller)
          az group create --name $(resourceGroup) --location $(location)

          # 2. Cluster var mı kontrol et
          exists=$(az aks list --query "[?name=='$(clusterName)' && resourceGroup=='$(resourceGroup)'] | length(@)")

          if [ "$exists" -eq "0" ]; then
            echo "--> AKS bulunamadı, yeni kurulum başlatılıyor..."
            az aks create \
              --resource-group $(resourceGroup) \
              --name $(clusterName) \
              --node-count 1 \
              --node-vm-size Standard_D2s_v3 \
              --generate-ssh-keys
          else
            echo "--> AKS zaten mevcut. Durumu kontrol ediliyor..."
            
            # Cluster 'Stopped' durumundaysa başlat
            powerState=$(az aks show --resource-group $(resourceGroup) --name $(clusterName) --query "powerState.code" -o tsv)
            if [ "$powerState" == "Stopped" ]; then
              echo "--> Cluster durdurulmuş, başlatılıyor..."
              az aks start --resource-group $(resourceGroup) --name $(clusterName)
            else
              echo "--> Cluster zaten çalışır durumda."
            fi
          fi

          # 3. Bağlantı bilgilerini al (kubectl komutları için hazır hale getir)
          az aks get-credentials --resource-group $(resourceGroup) --name $(clusterName) --overwrite-existing
          
          echo "--> Altyapı başarıyla hazırlandı!"